
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 11;
  public static final int IDENTIFIER = 105;
  public static final int TIMES = 85;
  public static final int LIMITED = 35;
  public static final int ARROW = 74;
  public static final int TYPE = 67;
  public static final int APOSTROPHE = 82;
  public static final int SUBTYPE = 61;
  public static final int ALIASED = 7;
  public static final int DOUBLE_STAR = 76;
  public static final int RAISE = 51;
  public static final int SEMI = 93;
  public static final int GET = 102;
  public static final int RENAMES = 55;
  public static final int UNTIL = 68;
  public static final int OVERRIDING = 45;
  public static final int ASSIGNMENT = 77;
  public static final int CPARENTHESIS = 84;
  public static final int ELSIF = 22;
  public static final int COMMA = 87;
  public static final int TERMINATE = 65;
  public static final int ALL = 8;
  public static final int DECLARE = 16;
  public static final int ABORT = 2;
  public static final int PUT = 101;
  public static final int ACCESS = 6;
  public static final int LOOP = 36;
  public static final int LOGICAL_OR = 92;
  public static final int COMPARE = 80;
  public static final int PROTECTED = 50;
  public static final int OUT = 44;
  public static final int FALSE = 95;
  public static final int NOT = 40;
  public static final int TASK = 64;
  public static final int ARRAY = 10;
  public static final int FLOAT = 97;
  public static final int STR = 106;
  public static final int THEN = 66;
  public static final int GOTO = 30;
  public static final int PACKAGE = 46;
  public static final int RECORD = 53;
  public static final int REVERSE = 58;
  public static final int MOD = 37;
  public static final int WHEN = 70;
  public static final int LOGICAL_AND = 81;
  public static final int GENERIC = 29;
  public static final int DIGITS = 19;
  public static final int SELECT = 59;
  public static final int OTHERS = 43;
  public static final int ABSTRACT = 4;
  public static final int SLASH = 90;
  public static final int TRUE = 94;
  public static final int RLABEL = 79;
  public static final int PLUS = 86;
  public static final int WHILE = 71;
  public static final int USE = 69;
  public static final int CHAR = 100;
  public static final int INTERFACE = 33;
  public static final int BOOLEAN = 98;
  public static final int LLABEL = 78;
  public static final int DO = 20;
  public static final int FOR = 27;
  public static final int RETURN = 57;
  public static final int DELAY = 17;
  public static final int ELSE = 21;
  public static final int BASED_LITERAL = 104;
  public static final int DOT = 89;
  public static final int INT = 96;
  public static final int PROCEDURE = 49;
  public static final int ENTRY = 24;
  public static final int DELTA = 18;
  public static final int PRAGMA = 47;
  public static final int NULL = 39;
  public static final int EOF = 0;
  public static final int FUNCTION = 28;
  public static final int MINUS = 88;
  public static final int IS = 34;
  public static final int CONSTANT = 15;
  public static final int BODY = 13;
  public static final int ACCEPT = 5;
  public static final int IN = 32;
  public static final int OR = 42;
  public static final int error = 1;
  public static final int EXIT = 26;
  public static final int DECIMAL_LITERAL = 103;
  public static final int SYNCHRONIZED = 62;
  public static final int IF = 31;
  public static final int OF = 41;
  public static final int ABS = 3;
  public static final int END = 23;
  public static final int COLON = 91;
  public static final int REM = 54;
  public static final int REQUEUE = 56;
  public static final int STR_TYP = 99;
  public static final int SEPARATE = 60;
  public static final int DOUBLE_DOT = 75;
  public static final int BEGIN = 12;
  public static final int CASE = 14;
  public static final int EXCEPTION = 25;
  public static final int NEW = 38;
  public static final int TAGGED = 63;
  public static final int RANGE = 52;
  public static final int AND = 9;
  public static final int PRIVATE = 48;
  public static final int WITH = 72;
  public static final int XOR = 73;
  public static final int OPARENTHESIS = 83;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABORT",
  "ABS",
  "ABSTRACT",
  "ACCEPT",
  "ACCESS",
  "ALIASED",
  "ALL",
  "AND",
  "ARRAY",
  "AT",
  "BEGIN",
  "BODY",
  "CASE",
  "CONSTANT",
  "DECLARE",
  "DELAY",
  "DELTA",
  "DIGITS",
  "DO",
  "ELSE",
  "ELSIF",
  "END",
  "ENTRY",
  "EXCEPTION",
  "EXIT",
  "FOR",
  "FUNCTION",
  "GENERIC",
  "GOTO",
  "IF",
  "IN",
  "INTERFACE",
  "IS",
  "LIMITED",
  "LOOP",
  "MOD",
  "NEW",
  "NULL",
  "NOT",
  "OF",
  "OR",
  "OTHERS",
  "OUT",
  "OVERRIDING",
  "PACKAGE",
  "PRAGMA",
  "PRIVATE",
  "PROCEDURE",
  "PROTECTED",
  "RAISE",
  "RANGE",
  "RECORD",
  "REM",
  "RENAMES",
  "REQUEUE",
  "RETURN",
  "REVERSE",
  "SELECT",
  "SEPARATE",
  "SUBTYPE",
  "SYNCHRONIZED",
  "TAGGED",
  "TASK",
  "TERMINATE",
  "THEN",
  "TYPE",
  "UNTIL",
  "USE",
  "WHEN",
  "WHILE",
  "WITH",
  "XOR",
  "ARROW",
  "DOUBLE_DOT",
  "DOUBLE_STAR",
  "ASSIGNMENT",
  "LLABEL",
  "RLABEL",
  "COMPARE",
  "LOGICAL_AND",
  "APOSTROPHE",
  "OPARENTHESIS",
  "CPARENTHESIS",
  "TIMES",
  "PLUS",
  "COMMA",
  "MINUS",
  "DOT",
  "SLASH",
  "COLON",
  "LOGICAL_OR",
  "SEMI",
  "TRUE",
  "FALSE",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "STR_TYP",
  "CHAR",
  "PUT",
  "GET",
  "DECIMAL_LITERAL",
  "BASED_LITERAL",
  "IDENTIFIER",
  "STR"
  };
}

